apiVersion: v1
kind: Service
metadata:
  name: recipes-svc
  namespace: prod
spec:
  type: nodePort
  selector:
    app: recipes
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
